### ISSUE TITLE
Cannot import BinaryWriter

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [LonamiWebs/Telebackup#13]
When I issue 

`python3 main.py`

I get:

`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from backuper import Backuper
  File "/home/me/Desktop/TG_BACKUP/Telebackup/backuper.py", line 17, in <module>
    from tl_database import TLDatabase
  File "/home/me/Desktop/TG_BACKUP/Telebackup/tl_database.py", line 12, in <module>
    from telethon.extensions import BinaryReader, BinaryWriter
ImportError: cannot import name 'BinaryWriter'`

**Comment by Lonami** [comment]
#11, #12. You could use an older version of Telethon though.
